-- Migration: Add performance_reports table for storing generated performance reports
-- This table stores performance analysis reports generated by the agentic service
-- The actual generation happens in Agentic_Python, but reports are retrieved via Backend_Python

CREATE TABLE IF NOT EXISTS performance_reports (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL,
    report_content TEXT NOT NULL,
    report_format VARCHAR(50) DEFAULT 'markdown',
    agent_statuses JSONB DEFAULT '{}',
    execution_log JSONB DEFAULT '[]',
    traces TEXT,
    trace_id VARCHAR(255),
    evidence_sufficient BOOLEAN DEFAULT false,
    evidence_quality_score DECIMAL(3,2) DEFAULT 0.0,
    retrieval_attempts INTEGER DEFAULT 0,
    errors JSONB DEFAULT '[]',
    success BOOLEAN DEFAULT false,
    processing_time_ms INTEGER,
    model_used VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast lookups by user
CREATE INDEX IF NOT EXISTS idx_performance_reports_uid ON performance_reports(uid);

-- Index for sorting by creation date
CREATE INDEX IF NOT EXISTS idx_performance_reports_created_at ON performance_reports(created_at DESC);

-- Add foreign key constraint to users table
ALTER TABLE performance_reports
ADD CONSTRAINT fk_performance_reports_user
FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE;
