"""add_question_generations_and_llm_tracking

Revision ID: 2d3eefae954c
Revises: 006
Create Date: 2025-11-15 14:16:15.180301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d3eefae954c'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('request_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_interactions_request_datetime'), 'llm_interactions', ['request_datetime'], unique=False)
    op.create_index(op.f('ix_llm_interactions_uid'), 'llm_interactions', ['uid'], unique=False)
    op.create_table('question_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('generation_date', sa.Date(), nullable=False),
    sa.Column('generation_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('llm_interaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['llm_interaction_id'], ['llm_interactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_generations_generation_date'), 'question_generations', ['generation_date'], unique=False)
    op.create_index(op.f('ix_question_generations_uid'), 'question_generations', ['uid'], unique=False)
    op.alter_column('attempts', 'uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('prompts', 'uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_prompts_created_at', table_name='prompts')
    op.drop_index('idx_prompts_uid', table_name='prompts')
    op.alter_column('question_patterns', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_blocking_history', 'blocked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_blocking_history', 'unblocked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_blocking_history_action', table_name='user_blocking_history')
    op.drop_index('idx_blocking_history_blocked_at', table_name='user_blocking_history')
    op.drop_index('idx_blocking_history_uid', table_name='user_blocking_history')
    op.create_index(op.f('ix_user_blocking_history_action'), 'user_blocking_history', ['action'], unique=False)
    op.create_index(op.f('ix_user_blocking_history_user_uid'), 'user_blocking_history', ['user_uid'], unique=False)
    op.alter_column('users', 'uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'subscription',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_users_is_blocked', table_name='users', postgresql_where='(is_blocked = true)')
    # Commented out: causes conflict with foreign keys created earlier
    # op.drop_constraint('users_uid_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_is_blocked'), 'users', ['is_blocked'], unique=False)
    # The unique constraint users_uid_key still exists, so we don't need to create a new unique index
    # op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # Commented out in upgrade, so also commenting in downgrade
    # op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_is_blocked'), table_name='users')
    # The unique constraint was never dropped, so no need to recreate it
    # op.create_unique_constraint('users_uid_key', 'users', ['uid'])
    op.create_index('idx_users_is_blocked', 'users', ['is_blocked'], unique=False, postgresql_where='(is_blocked = true)')
    op.alter_column('users', 'subscription',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_blocking_history_user_uid'), table_name='user_blocking_history')
    op.drop_index(op.f('ix_user_blocking_history_action'), table_name='user_blocking_history')
    op.create_index('idx_blocking_history_uid', 'user_blocking_history', ['user_uid'], unique=False)
    op.create_index('idx_blocking_history_blocked_at', 'user_blocking_history', [sa.literal_column('blocked_at DESC')], unique=False)
    op.create_index('idx_blocking_history_action', 'user_blocking_history', ['action'], unique=False)
    op.alter_column('user_blocking_history', 'unblocked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_blocking_history', 'blocked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('question_patterns', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_prompts_uid', 'prompts', ['uid'], unique=False)
    op.create_index('idx_prompts_created_at', 'prompts', ['created_at'], unique=False)
    op.alter_column('prompts', 'uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('attempts', 'uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_question_generations_uid'), table_name='question_generations')
    op.drop_index(op.f('ix_question_generations_generation_date'), table_name='question_generations')
    op.drop_table('question_generations')
    op.drop_index(op.f('ix_llm_interactions_uid'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_request_datetime'), table_name='llm_interactions')
    op.drop_table('llm_interactions')
    # ### end Alembic commands ###