from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, List

class MathAttempt(BaseModel):
    student_id: int
    uid: str #from Firbase Users table (User UID)
    datetime: datetime
    question: str
    is_answer_correct: bool
    incorrect_answer: Optional[str] = None
    correct_answer: str
    qorder: Optional[int] = None

class QuestionPattern(BaseModel):
    id: str
    type: str
    pattern_text: str
    created_at: datetime

class GenerateQuestionsRequest(BaseModel):
    uid: str
    level: Optional[int] = None  # Filter patterns by difficulty level
    ai_bridge_base_url: Optional[str] = None
    ai_bridge_api_key: Optional[str] = None
    ai_bridge_model: Optional[str] = None
    is_live: Optional[int] = 1  # 1=live from app, 0=test call (default: 1)

class UserRegistration(BaseModel):
    uid: str  # Firebase User UID (28 character alphanumeric string, e.g., "FrhUjcQpTDVKK14K4y3thVcPgQd2")
    email: str
    name: str
    displayName: str
    gradeLevel: int  # Grade level (4, 5, 6, 7)
    subscription: int = 0  # Subscription level: 0=free, 1=trial, 2+=premium
    registrationDate: Optional[str] = None  # ISO format datetime string (generated by backend if not provided)


# ============================================================================
# Knowledge-Based Question Game Schemas
# ============================================================================

class Subject(BaseModel):
    """Subject model for knowledge-based questions"""
    id: int
    name: str
    display_name: str
    description: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    is_active: bool = True


class KnowledgeDocument(BaseModel):
    """Knowledge document containing content for question generation"""
    id: int
    subject_id: int
    title: str
    content: str
    grade_level: Optional[int] = None
    source: Optional[str] = None
    is_active: bool = True


class GenerateKnowledgeQuestionsRequest(BaseModel):
    """Request body for generating knowledge-based questions"""
    uid: str
    subject_id: int
    count: int = Field(default=10, ge=1, le=50)  # 1-50 questions
    level: Optional[int] = None
    is_live: Optional[int] = 1


class KnowledgeQuestion(BaseModel):
    """A single knowledge-based question"""
    number: int
    topic: str
    question: str
    answer: str
    answer_type: str = "text"  # text, numeric, boolean
    difficulty: int = 1


class AnswerEvaluation(BaseModel):
    """Single answer for evaluation"""
    question: str
    user_answer: str
    correct_answer: str
    question_id: Optional[str] = None


class EvaluateAnswersRequest(BaseModel):
    """Request body for evaluating user answers"""
    uid: str
    subject_id: int
    evaluations: List[AnswerEvaluation]


class AnswerEvaluationResult(BaseModel):
    """Result of evaluating a single answer"""
    question_id: Optional[str] = None
    question: str
    user_answer: str
    correct_answer: str
    status: str  # 'correct', 'incorrect', 'partial'
    ai_feedback: str
    best_answer: str
    improvement_tips: Optional[str] = None
    score: Optional[float] = None  # 0.0 - 1.0

