from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, List

class MathAttempt(BaseModel):
    student_id: int
    uid: str #from Firbase Users table (User UID)
    datetime: datetime
    question: str
    is_answer_correct: bool
    incorrect_answer: Optional[str] = None
    correct_answer: str
    qorder: Optional[int] = None

class QuestionPattern(BaseModel):
    id: str
    type: str
    pattern_text: str
    created_at: datetime

class GenerateQuestionsRequest(BaseModel):
    uid: str
    level: Optional[int] = None  # Filter patterns by difficulty level
    ai_bridge_base_url: Optional[str] = None
    ai_bridge_api_key: Optional[str] = None
    ai_bridge_model: Optional[str] = None
    is_live: Optional[int] = 1  # 1=live from app, 0=test call (default: 1)

class UserRegistration(BaseModel):
    uid: str  # Firebase User UID (28 character alphanumeric string, e.g., "FrhUjcQpTDVKK14K4y3thVcPgQd2")
    email: str
    name: str
    displayName: str
    gradeLevel: int  # Grade level (4, 5, 6, 7)
    subscription: int = 0  # Subscription level: 0=free, 1=trial, 2+=premium
    credits: int = 10  # AI generation credits (10 for new users)
    registrationDate: Optional[str] = None  # ISO format datetime string (generated by backend if not provided)


class UserProfileUpdate(BaseModel):
    """Request body for updating user profile (name, displayName, gradeLevel)"""
    name: Optional[str] = Field(None, min_length=1, max_length=100, description="Student name")
    displayName: Optional[str] = Field(None, min_length=1, max_length=100, description="Display name")
    gradeLevel: Optional[int] = Field(None, ge=4, le=7, description="Grade level (4, 5, 6, or 7)")


# ============================================================================
# Knowledge-Based Question Game Schemas
# ============================================================================

class Subject(BaseModel):
    """Subject model for knowledge-based questions"""
    id: int
    name: str
    display_name: str
    description: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    is_active: bool = True


class KnowledgeDocument(BaseModel):
    """Knowledge document containing content for question generation"""
    id: int
    subject_id: int
    title: str
    content: str
    grade_level: Optional[int] = None
    source: Optional[str] = None
    is_active: bool = True


class GenerateKnowledgeQuestionsRequest(BaseModel):
    """Request body for generating knowledge-based questions"""
    uid: str
    subject_id: int
    count: int = Field(default=10, ge=1, le=50)  # 1-50 questions
    level: Optional[int] = None
    is_live: Optional[int] = 1


class KnowledgeQuestion(BaseModel):
    """A single knowledge-based question"""
    number: int
    topic: str
    question: str
    answer: str
    answer_type: str = "text"  # text, numeric, boolean
    difficulty: int = 1


class AnswerEvaluation(BaseModel):
    """Single answer for evaluation"""
    question: str
    user_answer: str
    correct_answer: str
    question_id: Optional[str] = None


class EvaluateAnswersRequest(BaseModel):
    """Request body for evaluating user answers"""
    uid: str
    subject_id: int
    evaluations: List[AnswerEvaluation]


class PerformanceReportQueryRequest(BaseModel):
    """Request body for performance report Q&A"""
    query: str = Field(..., min_length=3, max_length=500)
    subject_id: Optional[int] = None
    limit: int = Field(default=5, ge=1, le=20)


class AnswerEvaluationResult(BaseModel):
    """Result of evaluating a single answer"""
    question_id: Optional[str] = None
    question: str
    user_answer: str
    correct_answer: str
    status: str  # 'correct', 'incorrect', 'partial'
    ai_feedback: str
    best_answer: str
    improvement_tips: Optional[str] = None
    score: Optional[float] = None  # 0.0 - 1.0


# ============================================================================
# Question Help Schemas (Visual Aid Support)
# ============================================================================

class HelpStepVisual(BaseModel):
    """Visual aid for a help step (follows visual-questions plan structure)"""
    type: str  # 'rectangle', 'triangle', 'circle', 'square', 'fraction', 'number_line', 'clock', 'custom'
    data: dict  # Template-specific params: { width, height, unit, radius, etc. }
    svg: Optional[str] = None  # Only populated if AI-generated SVG enabled


class HelpStep(BaseModel):
    """A single step in the help explanation"""
    step_number: int
    title: str
    content: str  # Markdown-formatted content
    visual: Optional[HelpStepVisual] = None
    emoji: Optional[str] = None  # 🎯, 💡, ✅, etc.


class QuestionHelpRequest(BaseModel):
    """Request body for generating question help"""
    uid: str
    subject_id: int
    question: str
    topic: str
    difficulty: int
    answer: str
    is_pre_answer: bool  # True = help before answering, False = help after answering


class QuestionHelpResponse(BaseModel):
    """Response from help generation"""
    help_steps: List[HelpStep]
    similar_question: Optional[str] = None  # Only for pre-answer help
    ai_model: str
    tokens: int
    response_time_ms: int
    credits_remaining: int
    daily_help_count: int
    max_daily_help: int
    visual_count: int  # Number of JSON-based visuals
    svg_count: int  # Number of AI-generated SVGs


# ============================================================================
# Game Leaderboard Schemas
# ============================================================================

class GameScoreSubmit(BaseModel):
    """Request body for submitting a game score"""
    uid: str
    user_name: str  # Display name for leaderboard
    game_type: str  # 'multiplication_time' or 'multiplication_range'
    score: int  # Correct answers (time game) or used as secondary metric
    time_seconds: Optional[int] = None  # Completion time (range game)
    total_questions: Optional[int] = None


class GameScoreResponse(BaseModel):
    """A single game score for leaderboard display"""
    id: int
    uid: str
    user_name: str
    game_type: str
    score: int
    time_seconds: Optional[int] = None
    total_questions: Optional[int] = None
    created_at: str  # ISO format datetime string
    rank: Optional[int] = None  # Position in leaderboard


class LeaderboardResponse(BaseModel):
    """Response containing top scores for a game type"""
    game_type: str
    scores: List[GameScoreResponse]


# ============================================================================
# Admin Credits Management Schemas
# ============================================================================

class AdjustCreditsRequest(BaseModel):
    """Request body for adjusting user credits (admin endpoint)"""
    amount: int = Field(..., description="Credits to add (positive) or remove (negative)")
    reason: Optional[str] = Field(None, max_length=255, description="Reason for adjustment")


# ============================================================================
# LLM Models Schemas
# ============================================================================

class LLMModelSchema(BaseModel):
    """Response schema for an LLM model"""
    id: int
    model_name: str
    display_name: Optional[str] = None
    provider: str
    model_type: Optional[str] = None
    version: Optional[str] = None
    order_number: int
    active: bool
    deprecated: bool
    manual: bool
    last_seen_at: Optional[str] = None  # ISO format datetime
    created_at: str  # ISO format datetime
    updated_at: str  # ISO format datetime


class LLMModelUpdate(BaseModel):
    """Request body for updating an LLM model (admin endpoint)"""
    order_number: Optional[int] = Field(None, ge=0, description="Display order")
    active: Optional[bool] = Field(None, description="Whether the model is active")
    manual: Optional[bool] = Field(None, description="Whether the model is manually managed")
    display_name: Optional[str] = Field(None, max_length=150, description="Human-readable name")


class LLMModelSyncRequest(BaseModel):
    """Request body for syncing LLM models from a provider"""
    provider: str = Field(..., description="Provider to sync from: 'google', 'groq', 'anthropic'")
    api_key: Optional[str] = Field(None, description="API key for the provider (optional, uses env var if not provided)")


class LLMModelSyncResult(BaseModel):
    """Response schema for LLM model sync operation"""
    success: bool
    provider: str
    models_added: int
    models_updated: int
    models_deprecated: int
    message: str


