name: Deploy to Supabase

on:
  push:
    branches:
      - main  # or change to master, depending on your default branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Run database setup
        id: db_setup
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DATABASE_PROVIDER: supabase
        run: |
          python setup_supabase_schema.py
          
      - name: Run database migrations
        if: success() && steps.db_setup.outcome == 'success'
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DATABASE_PROVIDER: supabase
          DATABASE_URL: ${{ secrets.DATABASE_URL || '' }}
        run: |
          if [ -d "migrations" ] && [ -f "migrations/alembic.ini" ]; then
            # Run alembic from the project root with the config file path
            alembic -c migrations/alembic.ini upgrade head
          fi
          
      - name: Check for deployment success
        if: ${{ success() }}
        run: |
          echo "✅ Deployment to Supabase successful!"
          
      - name: Handle deployment failure
        if: ${{ failure() }}
        run: |
          echo "❌ Deployment to Supabase failed!"
          # You could add notification steps here