name: Deploy to Supabase

on:
  push:
    branches:
      - main  # or change to master, depending on your default branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Run database setup
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DATABASE_PROVIDER: supabase
        run: |
          python setup_supabase_schema.py
          
      - name: Run database migrations
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DATABASE_PROVIDER: supabase
        run: |
          if [ -d "migrations" ] && [ -f "migrations/alembic.ini" ]; then
            # Don't cd into migrations, run alembic from the project root with the config file path
            alembic -c migrations/alembic.ini upgrade head
          fi