name: Deploy to Supabase

on:
  push:
    branches:
      - main  # or change to master, depending on your default branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install psycopg2 for direct PostgreSQL connections
          pip install psycopg2-binary
          
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Check database schema
        id: db_check
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DATABASE_PROVIDER: supabase
        run: |
          # Run the setup_supabase_schema.py script to check if schema exists
          # It will print message if table exists or create it otherwise
          python setup_supabase_schema.py
          
      - name: Set PostgreSQL connection string
        run: |
          # Set the explicit PostgreSQL connection string
          echo "POSTGRES_CONNECTION_STRING=postgresql://postgres:${{ secrets.SUPABASE_DB_PASSWORD }}@db.apifyzsbctxzfwrqkcqb.supabase.co:5432/postgres" >> $GITHUB_ENV
          
      - name: Mark migrations as applied
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
        run: |
          alembic -c migrations/alembic.ini stamp head
          
      - name: Run database migrations
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
        run: |
          alembic -c migrations/alembic.ini upgrade head
          
      - name: Check for deployment success
        if: ${{ success() }}
        run: |
          echo "✅ Deployment to Supabase successful!"
          
      - name: Handle deployment failure
        if: ${{ failure() }}
        run: |
          echo "❌ Deployment to Supabase failed!"